SELECT
poliza,
placa,
clave_intermediario,
sucursal,
regional,
prima_ant,
prima_renov,
descuento,
cedula_asegurado,
documento,
nombre,
trat_datos,
IF(telefono regexp '^(3[0-9]{9}|60[0-9]{8})$', telefono, NULL) AS telefono,
IF(telefono2 regexp '^(3[0-9]{9}|60[0-9]{8})$', telefono2, NULL) AS telefono2,
IF(telefono3 regexp '^(3[0-9]{9}|60[0-9]{8})$', telefono3, NULL) AS telefono3,
email,
nombre_intermediario,
cliente_activo,
fecha_utima_renovacion,
poliza_vigente,
fecha_asignacion,
anio,
periodo,
nombre_base,
hoja,
doc_tomador,
id,
lepd
FROM bbdd_cos_bog_allianz.tb_asignacion_renovaciones_autos;